services:
  memevault:
    build: .
    container_name: memevault
    restart: unless-stopped
    environment:
      - PORT=3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ifunny.rule=Host(`ifunny.oddlayer.tech`)"
      - "traefik.http.routers.ifunny.entrypoints=websecure"
      - "traefik.http.routers.ifunny.tls.certresolver=letsencrypt"
      - "traefik.http.services.ifunny.loadbalancer.server.port=3000"
    networks:
      - n8n_default

networks:
  n8n_default:
    external: true
